# SPDX-License-Identifier: GPL-2.0-only

# Makefile for the focaltech touchscreen drivers.


obj-$(CONFIG_TOUCHSCREEN_FTS_NEW)	+=  focaltech_core.o
obj-$(CONFIG_TOUCHSCREEN_FTS_NEW)	+=  focaltech_ex_fun.o
obj-$(CONFIG_TOUCHSCREEN_FTS_NEW)	+=  focaltech_ex_mode.o
obj-$(CONFIG_TOUCHSCREEN_FTS_NEW)	+=  focaltech_gesture.o
obj-$(CONFIG_TOUCHSCREEN_FTS_NEW)	+=  focaltech_esdcheck.o
obj-$(CONFIG_TOUCHSCREEN_FTS_NEW)	+=  focaltech_point_report_check.o

obj-$(CONFIG_TOUCHSCREEN_FTS_NEW)	+=  focaltech_i2c.o
obj-$(CONFIG_TOUCHSCREEN_FTS_NEW)	+=  focaltech_flash.o
obj-$(CONFIG_TOUCHSCREEN_FTS_NEW)	+=  focaltech_flash/
